apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: gcr.io/concrete-198923/jenkins-master
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JENKINS_OPTS
          valueFrom:
            secretKeyRef:
              name: jenkins
              key: options
        - name: JAVA_OPTS
          value: '-Xmx1500m'
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
                volumeMounts:
        resources:
          limits:
            cpu: 500m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 2000Mi
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
